services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend/score-counter-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CI=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - NODE_OPTIONS=--no-deprecation
    volumes:
      - ./frontend/score-counter-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
